package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Bar;
import org.mybatis.cdi.Mapper;

@Mapper
public interface BarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAR
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAR
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    int insert(Bar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAR
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    Bar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAR
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    List<Bar> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAR
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    int updateByPrimaryKey(Bar record);
}