package lt.vu.mybatis.model;

public class Section {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SECTION.ID
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SECTION.MAXWORKERS
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    private Double maxworkers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SECTION.NAME
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SECTION.OPT_LOCK_VERSION
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    private Integer optLockVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SECTION.BAR_ID
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    private Integer barId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SECTION.ID
     *
     * @return the value of PUBLIC.SECTION.ID
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SECTION.ID
     *
     * @param id the value for PUBLIC.SECTION.ID
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SECTION.MAXWORKERS
     *
     * @return the value of PUBLIC.SECTION.MAXWORKERS
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    public Double getMaxworkers() {
        return maxworkers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SECTION.MAXWORKERS
     *
     * @param maxworkers the value for PUBLIC.SECTION.MAXWORKERS
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    public void setMaxworkers(Double maxworkers) {
        this.maxworkers = maxworkers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SECTION.NAME
     *
     * @return the value of PUBLIC.SECTION.NAME
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SECTION.NAME
     *
     * @param name the value for PUBLIC.SECTION.NAME
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SECTION.OPT_LOCK_VERSION
     *
     * @return the value of PUBLIC.SECTION.OPT_LOCK_VERSION
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    public Integer getOptLockVersion() {
        return optLockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SECTION.OPT_LOCK_VERSION
     *
     * @param optLockVersion the value for PUBLIC.SECTION.OPT_LOCK_VERSION
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    public void setOptLockVersion(Integer optLockVersion) {
        this.optLockVersion = optLockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SECTION.BAR_ID
     *
     * @return the value of PUBLIC.SECTION.BAR_ID
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    public Integer getBarId() {
        return barId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SECTION.BAR_ID
     *
     * @param barId the value for PUBLIC.SECTION.BAR_ID
     *
     * @mbg.generated Sun May 17 19:10:23 EEST 2020
     */
    public void setBarId(Integer barId) {
        this.barId = barId;
    }
}